apiVersion: apps/v1 
kind: Deployment
metadata:
  name: tm-app
  labels: 
     app: tm

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: tm

  template:
    metadata:
      labels:
        app: tm
    spec:
      containers:
      - name: tm-d
        image: eshwarv5/tm-d
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
